<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LEVCAN.NET\LEVCAN.NET.csproj" />
    <ProjectReference Include="..\LEVCAN Configurator Shared\LEVCAN Configurator Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\LEVCAN Configurator\Helpers\FrameRateLimiter.cs" Link="FrameRateLimiter.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll" Condition="Exists('..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll')">
      <Link>runtimes\win-x64\native\LEVCANlib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll" Condition="Exists('..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll')">
      <Link>LEVCANlib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Bin\Release\runtimes\win-x64\native\LEVCANlib.dll" Condition="!Exists('..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll') and Exists('..\Bin\Release\runtimes\win-x64\native\LEVCANlib.dll')">
      <Link>runtimes\win-x64\native\LEVCANlib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Bin\Release\runtimes\win-x64\native\LEVCANlib.dll" Condition="!Exists('..\Bin\$(Configuration)\runtimes\win-x64\native\LEVCANlib.dll') and Exists('..\Bin\Release\runtimes\win-x64\native\LEVCANlib.dll')">
      <Link>LEVCANlib.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
